package Vistas;

import java.net.URL;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.ImageIcon;

public class Menu extends javax.swing.JFrame {

    private boolean memFlag = false;
    private boolean socFlag = false;
    private boolean entFlag = false;
    private boolean claFlag = false;
    private boolean asFlag = false;
    ArrayList<String> frases = new ArrayList<>();

    //============== CONSTRUCTOR ================
    public Menu() {
        initComponents();

        try {
            //membresia
            URL imagenMembresia = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/37fa8fa4d270cd25a3339014b742db8329d0ec87/ProyectoFinal_LAB1/Botones/Botones_sin_pulsar/MEMBRES%C3%8DA_MENU.png");
            ImageIcon iconMembresia = new ImageIcon(imagenMembresia);
            lblMembresia.setIcon(iconMembresia);
            // socios
            URL imagenSocios = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/37fa8fa4d270cd25a3339014b742db8329d0ec87/ProyectoFinal_LAB1/Botones/Botones_sin_pulsar/SOCIOS_MENU.png");
            ImageIcon iconSocio = new ImageIcon(imagenSocios);
            lblSocios.setIcon(iconSocio);
            // clases
            URL imagenClases = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/main/ProyectoFinal_LAB1/src/Botones/Botones_sin_pulsar/CLASES_MENU.png");
            ImageIcon iconClase = new ImageIcon(imagenClases);
            lblClases.setIcon(iconClase);
            // asistencia
            URL imagenAsistencia = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/main/ProyectoFinal_LAB1/src/Botones/Botones_sin_pulsar/ASISTENCIA_MENU.png");
            ImageIcon iconAsistencia = new ImageIcon(imagenAsistencia);
            lblAsistencia.setIcon(iconAsistencia);
            // entrenador 
            URL imagenEntrenador = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/37fa8fa4d270cd25a3339014b742db8329d0ec87/ProyectoFinal_LAB1/Botones/Botones_sin_pulsar/ENTRENADOR_MENU.png");
            ImageIcon iconEntrenador = new ImageIcon(imagenEntrenador);
            lblEntrenador.setIcon(iconEntrenador);

            // ICONO DE LA APP
            setIconImage(new ImageIcon(getClass().getResource("/Botones/Botones_internos/logoGYM.png")).getImage());

        } catch (Exception e) {
            System.out.println("no " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpFondoBtn = new javax.swing.JPanel();
        lblSocios = new javax.swing.JLabel();
        lblEntrenador = new javax.swing.JLabel();
        lblClases = new javax.swing.JLabel();
        lblMembresia = new javax.swing.JLabel();
        lblAsistencia = new javax.swing.JLabel();
        jlLogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        escritorio = new javax.swing.JPanel();
        lblFrases = new javax.swing.JLabel();
        jlFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GYM");
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        jpFondoBtn.setBackground(new java.awt.Color(102, 102, 102));
        jpFondoBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSocios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSociosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSociosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSociosMouseExited(evt);
            }
        });
        jpFondoBtn.add(lblSocios, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 210, 67));

        lblEntrenador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEntrenadorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEntrenadorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEntrenadorMouseExited(evt);
            }
        });
        jpFondoBtn.add(lblEntrenador, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 210, 67));

        lblClases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClasesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblClasesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblClasesMouseExited(evt);
            }
        });
        jpFondoBtn.add(lblClases, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 210, 67));

        lblMembresia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMembresiaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMembresiaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMembresiaMouseExited(evt);
            }
        });
        jpFondoBtn.add(lblMembresia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 210, 67));

        lblAsistencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAsistenciaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAsistenciaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAsistenciaMouseExited(evt);
            }
        });
        jpFondoBtn.add(lblAsistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 210, 67));

        jlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Botones_internos/Logo.png"))); // NOI18N
        jlLogo.setText("jLabel1");
        jlLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlLogoMouseReleased(evt);
            }
        });
        jpFondoBtn.add(jlLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 180, 160));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Botones_internos/Brackground_menu.png"))); // NOI18N
        jpFondoBtn.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 680));

        escritorio.setBackground(new java.awt.Color(214, 236, 225));
        escritorio.setPreferredSize(new java.awt.Dimension(1100, 0));
        escritorio.setLayout(null);

        lblFrases.setFont(new java.awt.Font("Edo", 1, 30)); // NOI18N
        lblFrases.setForeground(new java.awt.Color(0, 51, 51));
        lblFrases.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFrases.setText("Frase del dia");
        lblFrases.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        escritorio.add(lblFrases);
        lblFrases.setBounds(50, 40, 920, 103);

        jlFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Botones_internos/Brackground.png"))); // NOI18N
        escritorio.add(jlFondo);
        jlFondo.setBounds(0, 0, 1018, 680);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpFondoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 1021, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpFondoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 675, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblMembresiaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMembresiaMouseEntered

        try {
            URL imagenMembresia = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/main/ProyectoFinal_LAB1/src/Botones/Botones_pulsados/MEMBRES%C3%8DA.png");
            ImageIcon iconMembresia = new ImageIcon(imagenMembresia);
            lblMembresia.setIcon(iconMembresia);
        } catch (Exception e) {
        }

    }//GEN-LAST:event_lblMembresiaMouseEntered

    private void lblMembresiaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMembresiaMouseExited
        if (!memFlag) {

            try {
                URL imagenMembresia = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/37fa8fa4d270cd25a3339014b742db8329d0ec87/ProyectoFinal_LAB1/Botones/Botones_sin_pulsar/MEMBRES%C3%8DA_MENU.png");
                ImageIcon iconMembresia = new ImageIcon(imagenMembresia);
                lblMembresia.setIcon(iconMembresia);
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_lblMembresiaMouseExited

    private void lblSociosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSociosMouseEntered
        try {
            URL imagenSocios = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/main/ProyectoFinal_LAB1/src/Botones/Botones_pulsados/SOCIOS.png");
            ImageIcon iconSocio = new ImageIcon(imagenSocios);
            lblSocios.setIcon(iconSocio);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_lblSociosMouseEntered

    private void lblSociosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSociosMouseExited
        if (!socFlag) {

            try {
                URL imagenSocios = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/37fa8fa4d270cd25a3339014b742db8329d0ec87/ProyectoFinal_LAB1/Botones/Botones_sin_pulsar/SOCIOS_MENU.png");
                ImageIcon iconSocio = new ImageIcon(imagenSocios);
                lblSocios.setIcon(iconSocio);
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_lblSociosMouseExited

    private void lblClasesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClasesMouseEntered
        try {
            URL imagenClases = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/main/ProyectoFinal_LAB1/src/Botones/Botones_pulsados/CLASES.png");
            ImageIcon iconClase = new ImageIcon(imagenClases);
            lblClases.setIcon(iconClase);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_lblClasesMouseEntered

    private void lblClasesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClasesMouseExited
        if (!claFlag) {

            try {
                URL imagenClases = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/main/ProyectoFinal_LAB1/src/Botones/Botones_sin_pulsar/CLASES_MENU.png");
                ImageIcon iconClase = new ImageIcon(imagenClases);
                lblClases.setIcon(iconClase);
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_lblClasesMouseExited

    private void lblAsistenciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAsistenciaMouseExited
        if (!asFlag) {

            try {
                URL imagenAsistencia = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/main/ProyectoFinal_LAB1/src/Botones/Botones_sin_pulsar/ASISTENCIA_MENU.png");
                ImageIcon iconAsistencia = new ImageIcon(imagenAsistencia);
                lblAsistencia.setIcon(iconAsistencia);
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_lblAsistenciaMouseExited

    private void lblAsistenciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAsistenciaMouseEntered
        try {
            URL imagenAsistencia = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/main/ProyectoFinal_LAB1/src/Botones/Botones_pulsados/ASISTENCIA.png");
            ImageIcon iconAsistencia = new ImageIcon(imagenAsistencia);
            lblAsistencia.setIcon(iconAsistencia);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_lblAsistenciaMouseEntered

    private void lblEntrenadorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEntrenadorMouseExited
        if (!entFlag) {

            try {
                URL imagenEntrenador = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/37fa8fa4d270cd25a3339014b742db8329d0ec87/ProyectoFinal_LAB1/Botones/Botones_sin_pulsar/ENTRENADOR_MENU.png");
                ImageIcon iconEntrenador = new ImageIcon(imagenEntrenador);
                lblEntrenador.setIcon(iconEntrenador);

            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_lblEntrenadorMouseExited

    private void lblEntrenadorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEntrenadorMouseEntered
        try {
            URL imagenEntrenador = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/main/ProyectoFinal_LAB1/src/Botones/Botones_pulsados/ENTRENADOR.png");
            ImageIcon iconEntrenador = new ImageIcon(imagenEntrenador);
            lblEntrenador.setIcon(iconEntrenador);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_lblEntrenadorMouseEntered

    private void lblMembresiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMembresiaMouseClicked
        despintarTodos();
        memFlag = true;
        socFlag = false;
        asFlag = false;
        entFlag = false;
        claFlag = false;
        try {
            URL imagenMembresia = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/main/ProyectoFinal_LAB1/src/Botones/Botones_pulsados/MEMBRES%C3%8DA.png");
            ImageIcon iconMembresia = new ImageIcon(imagenMembresia);
            lblMembresia.setIcon(iconMembresia);
        } catch (Exception e) {
        }
        escritorio.removeAll();
        escritorio.repaint();
        VistaMembresia m = new VistaMembresia();
        m.setVisible(true);
        escritorio.add(m);
        m.moveToFront();

        try {
            m.setMaximum(true);
        } catch (Exception e) {
        }

    }//GEN-LAST:event_lblMembresiaMouseClicked

    private void lblSociosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSociosMouseClicked
        despintarTodos();
        memFlag = false;
        socFlag = true;
        asFlag = false;
        entFlag = false;
        claFlag = false;
        try {
            URL imagenSocios = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/main/ProyectoFinal_LAB1/src/Botones/Botones_pulsados/SOCIOS.png");
            ImageIcon iconSocio = new ImageIcon(imagenSocios);
            lblSocios.setIcon(iconSocio);
        } catch (Exception e) {
        }
        escritorio.removeAll();
        escritorio.repaint();
        VistaSocio s = new VistaSocio();
        s.setVisible(true);
        escritorio.add(s);
        s.moveToFront();

        try {
            s.setMaximum(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_lblSociosMouseClicked

    private void lblClasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClasesMouseClicked
        despintarTodos();
        memFlag = false;
        socFlag = false;
        asFlag = false;
        entFlag = false;
        claFlag = true;
        try {
            URL imagenSocios = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/main/ProyectoFinal_LAB1/src/Botones/Botones_pulsados/CLASES.png");
            ImageIcon iconSocio = new ImageIcon(imagenSocios);
            lblClases.setIcon(iconSocio);
        } catch (Exception e) {
        }
        escritorio.removeAll();
        escritorio.repaint();
        VistaClase c = new VistaClase();
        c.setVisible(true);
        escritorio.add(c);
        c.moveToFront();

        try {
            c.setMaximum(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_lblClasesMouseClicked

    private void lblAsistenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAsistenciaMouseClicked
        despintarTodos();
        memFlag = false;
        socFlag = false;
        asFlag = true;
        entFlag = false;
        claFlag = false;
        try {
            URL imagenSocios = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/main/ProyectoFinal_LAB1/src/Botones/Botones_pulsados/ASISTENCIA.png");
            ImageIcon iconSocio = new ImageIcon(imagenSocios);
            lblAsistencia.setIcon(iconSocio);
        } catch (Exception e) {
        }
        escritorio.removeAll();
        escritorio.repaint();
        VistaAsisencia a = new VistaAsisencia();
        a.setVisible(true);
        escritorio.add(a);
        a.moveToFront();

        try {
            a.setMaximum(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_lblAsistenciaMouseClicked

    private void lblEntrenadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEntrenadorMouseClicked
        despintarTodos();
        memFlag = false;
        socFlag = false;
        asFlag = false;
        entFlag = true;
        claFlag = false;
        try {
            URL imagenSocios = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/main/ProyectoFinal_LAB1/src/Botones/Botones_pulsados/ENTRENADOR.png");
            ImageIcon iconSocio = new ImageIcon(imagenSocios);
            lblEntrenador.setIcon(iconSocio);
        } catch (Exception e) {
        }
        escritorio.removeAll();
        escritorio.repaint();
        VistaEntrenador e = new VistaEntrenador();
        e.setVisible(true);
        escritorio.add(e);
        e.moveToFront();

        try {
            e.setMaximum(true);
        } catch (Exception f) {
        }

    }//GEN-LAST:event_lblEntrenadorMouseClicked

    private void jlLogoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlLogoMouseReleased
        escritorio.removeAll();
        escritorio.repaint();
        fraseDiaria();
        escritorio.add(lblFrases);
        escritorio.add(jlFondo);


    }//GEN-LAST:event_jlLogoMouseReleased

    public void despintarTodos() {
        //membresia
        try {
            URL imagenMembresia = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/37fa8fa4d270cd25a3339014b742db8329d0ec87/ProyectoFinal_LAB1/Botones/Botones_sin_pulsar/MEMBRES%C3%8DA_MENU.png");
            ImageIcon iconMembresia = new ImageIcon(imagenMembresia);
            lblMembresia.setIcon(iconMembresia);
        } catch (Exception e) {
        }
        //socio
        try {
            URL imagenSocios = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/37fa8fa4d270cd25a3339014b742db8329d0ec87/ProyectoFinal_LAB1/Botones/Botones_sin_pulsar/SOCIOS_MENU.png");
            ImageIcon iconSocio = new ImageIcon(imagenSocios);
            lblSocios.setIcon(iconSocio);
        } catch (Exception e) {
        }
        //clases
        try {
            URL imagenClases = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/main/ProyectoFinal_LAB1/src/Botones/Botones_sin_pulsar/CLASES_MENU.png");
            ImageIcon iconClase = new ImageIcon(imagenClases);
            lblClases.setIcon(iconClase);
        } catch (Exception e) {
        }
        //asistencia
        try {
            URL imagenAsistencia = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/main/ProyectoFinal_LAB1/src/Botones/Botones_sin_pulsar/ASISTENCIA_MENU.png");
            ImageIcon iconAsistencia = new ImageIcon(imagenAsistencia);
            lblAsistencia.setIcon(iconAsistencia);
        } catch (Exception e) {
        }
        // entrenador
        try {
            URL imagenEntrenador = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/37fa8fa4d270cd25a3339014b742db8329d0ec87/ProyectoFinal_LAB1/Botones/Botones_sin_pulsar/ENTRENADOR_MENU.png");
            ImageIcon iconEntrenador = new ImageIcon(imagenEntrenador);
            lblEntrenador.setIcon(iconEntrenador);

        } catch (Exception e) {
        }
    }

    private void fraseDiaria() {
        frases.add("No pain, no gain.");
        frases.add("El dolor es temporal, la gloria es para siempre.");
        frases.add("Hazlo por el '¡wow!' que vendrá después.");
        frases.add("Nunca es tarde para empezar.");
        frases.add("Tú contra ti mismo. Sé tu mejor versión.");
        frases.add("Cada día es una nueva oportunidad para mejorar.");
        frases.add("El éxito es la suma de pequeños esfuerzos repetidos día tras día.");
        frases.add("No cuentes los días, haz que los días cuenten.");
        frases.add("Eres más fuerte de lo que piensas.");
        frases.add("Tu único límite eres tú mismo.");
        frases.add("El dolor que sientes hoy será la fuerza que sentirás mañana.");
     
        frases.add("El cuerpo logra lo que la mente cree.");
        frases.add("Hazlo con pasión o no lo hagas.");
        frases.add("No se trata de ser el mejor, se trata de ser mejor que ayer.");
        frases.add("La disciplina es el puente entre tus metas y tus logros.");
        frases.add("No te detengas hasta que estés orgulloso.");
        frases.add("Cuida tu cuerpo, es el único lugar que tienes para vivir.");
        frases.add("Si no te desafía, no te cambia.");
        
        frases.add("Entrena duro o vete a casa.");
        frases.add("El único mal entrenamiento es el que no se hace.");
        frases.add("Transforma tu cuerpo, transforma tu vida.");
        frases.add("Esfuérzate un poco más cada día.");
        frases.add("Los resultados no se obtienen con excusas.");
        frases.add("Nunca te rindas en lo que realmente quieres hacer.");
        frases.add("El cuerpo logra lo que la mente cree.");
        frases.add("La única manera de hacer un gran trabajo es amar lo que haces.");

        Collections.shuffle(frases);
        lblFrases.setText(frases.get(0));

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel escritorio;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jlFondo;
    private javax.swing.JLabel jlLogo;
    private javax.swing.JPanel jpFondoBtn;
    private javax.swing.JLabel lblAsistencia;
    private javax.swing.JLabel lblClases;
    private javax.swing.JLabel lblEntrenador;
    private javax.swing.JLabel lblFrases;
    private javax.swing.JLabel lblMembresia;
    private javax.swing.JLabel lblSocios;
    // End of variables declaration//GEN-END:variables
}
