
package Vistas;

import java.awt.Event;
import java.io.File;
import java.net.URL;
import javax.swing.Icon;
import javax.swing.ImageIcon;


public class Menu extends javax.swing.JFrame {

    private boolean memFlag = false;
    private boolean socFlag = false;
    private boolean entFlag = false;
    private boolean claFlag = false;
    private boolean asFlag = false;

    public Menu() {
        initComponents();
        try {
            //membresia
            URL imagenMembresia = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/37fa8fa4d270cd25a3339014b742db8329d0ec87/ProyectoFinal_LAB1/Botones/Botones_sin_pulsar/MEMBRES%C3%8DA_MENU.png");
            ImageIcon iconMembresia = new ImageIcon(imagenMembresia);
            lblMembresia.setIcon(iconMembresia);
            // socios
            URL imagenSocios = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/37fa8fa4d270cd25a3339014b742db8329d0ec87/ProyectoFinal_LAB1/Botones/Botones_sin_pulsar/SOCIOS_MENU.png");
            ImageIcon iconSocio = new ImageIcon(imagenSocios);
            lblSocios.setIcon(iconSocio);
            // clases
            URL imagenClases = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/main/ProyectoFinal_LAB1/src/Botones/Botones_sin_pulsar/CLASES_MENU.png");
            ImageIcon iconClase = new ImageIcon(imagenClases);
            lblClases.setIcon(iconClase);
            // asistencia
            URL imagenAsistencia = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/main/ProyectoFinal_LAB1/src/Botones/Botones_sin_pulsar/ASISTENCIA_MENU.png");
            ImageIcon iconAsistencia = new ImageIcon(imagenAsistencia);
            lblAsistencia.setIcon(iconAsistencia);
            // entrenador 
            URL imagenEntrenador = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/37fa8fa4d270cd25a3339014b742db8329d0ec87/ProyectoFinal_LAB1/Botones/Botones_sin_pulsar/ENTRENADOR_MENU.png");
            ImageIcon iconEntrenador = new ImageIcon(imagenEntrenador);
            lblEntrenador.setIcon(iconEntrenador);

        } catch (Exception e) {
            System.out.println("no " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpFondoBtn = new javax.swing.JPanel();
        lblEntrenador = new javax.swing.JLabel();
        lblMembresia = new javax.swing.JLabel();
        lblSocios = new javax.swing.JLabel();
        lblClases = new javax.swing.JLabel();
        lblAsistencia = new javax.swing.JLabel();
        escritorio = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));

        jpFondoBtn.setBackground(new java.awt.Color(102, 102, 102));

        lblEntrenador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEntrenadorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEntrenadorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEntrenadorMouseExited(evt);
            }
        });

        lblMembresia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMembresiaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMembresiaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMembresiaMouseExited(evt);
            }
        });

        lblSocios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSociosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSociosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSociosMouseExited(evt);
            }
        });

        lblClases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClasesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblClasesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblClasesMouseExited(evt);
            }
        });

        lblAsistencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAsistenciaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAsistenciaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAsistenciaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpFondoBtnLayout = new javax.swing.GroupLayout(jpFondoBtn);
        jpFondoBtn.setLayout(jpFondoBtnLayout);
        jpFondoBtnLayout.setHorizontalGroup(
            jpFondoBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondoBtnLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jpFondoBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMembresia, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSocios, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClases, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jpFondoBtnLayout.setVerticalGroup(
            jpFondoBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFondoBtnLayout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addComponent(lblMembresia, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblSocios, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblClases, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(lblEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );

        escritorio.setBackground(new java.awt.Color(214, 236, 225));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1023, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpFondoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFondoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblMembresiaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMembresiaMouseEntered

        try {
            URL imagenMembresia = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/main/ProyectoFinal_LAB1/src/Botones/Botones_pulsados/MEMBRES%C3%8DA.png");
            ImageIcon iconMembresia = new ImageIcon(imagenMembresia);
            lblMembresia.setIcon(iconMembresia);
        } catch (Exception e) {
        }

    }//GEN-LAST:event_lblMembresiaMouseEntered

    private void lblMembresiaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMembresiaMouseExited
        if (!memFlag) {

            try {
                URL imagenMembresia = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/37fa8fa4d270cd25a3339014b742db8329d0ec87/ProyectoFinal_LAB1/Botones/Botones_sin_pulsar/MEMBRES%C3%8DA_MENU.png");
                ImageIcon iconMembresia = new ImageIcon(imagenMembresia);
                lblMembresia.setIcon(iconMembresia);
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_lblMembresiaMouseExited

    private void lblSociosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSociosMouseEntered
        try {
            URL imagenSocios = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/main/ProyectoFinal_LAB1/src/Botones/Botones_pulsados/SOCIOS.png");
            ImageIcon iconSocio = new ImageIcon(imagenSocios);
            lblSocios.setIcon(iconSocio);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_lblSociosMouseEntered

    private void lblSociosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSociosMouseExited
        if (!socFlag) {

            try {
                URL imagenSocios = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/37fa8fa4d270cd25a3339014b742db8329d0ec87/ProyectoFinal_LAB1/Botones/Botones_sin_pulsar/SOCIOS_MENU.png");
                ImageIcon iconSocio = new ImageIcon(imagenSocios);
                lblSocios.setIcon(iconSocio);
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_lblSociosMouseExited

    private void lblClasesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClasesMouseEntered
        try {
            URL imagenClases = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/main/ProyectoFinal_LAB1/src/Botones/Botones_pulsados/CLASES.png");
            ImageIcon iconClase = new ImageIcon(imagenClases);
            lblClases.setIcon(iconClase);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_lblClasesMouseEntered

    private void lblClasesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClasesMouseExited
        if (!claFlag) {

            try {
                URL imagenClases = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/main/ProyectoFinal_LAB1/src/Botones/Botones_sin_pulsar/CLASES_MENU.png");
                ImageIcon iconClase = new ImageIcon(imagenClases);
                lblClases.setIcon(iconClase);
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_lblClasesMouseExited

    private void lblAsistenciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAsistenciaMouseExited
        if (!asFlag) {

            try {
                URL imagenAsistencia = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/main/ProyectoFinal_LAB1/src/Botones/Botones_sin_pulsar/ASISTENCIA_MENU.png");
                ImageIcon iconAsistencia = new ImageIcon(imagenAsistencia);
                lblAsistencia.setIcon(iconAsistencia);
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_lblAsistenciaMouseExited

    private void lblAsistenciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAsistenciaMouseEntered
        try {
            URL imagenAsistencia = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/main/ProyectoFinal_LAB1/src/Botones/Botones_pulsados/ASISTENCIA.png");
            ImageIcon iconAsistencia = new ImageIcon(imagenAsistencia);
            lblAsistencia.setIcon(iconAsistencia);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_lblAsistenciaMouseEntered

    private void lblEntrenadorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEntrenadorMouseExited
        if (!entFlag) {

            try {
                URL imagenEntrenador = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/37fa8fa4d270cd25a3339014b742db8329d0ec87/ProyectoFinal_LAB1/Botones/Botones_sin_pulsar/ENTRENADOR_MENU.png");
                ImageIcon iconEntrenador = new ImageIcon(imagenEntrenador);
                lblEntrenador.setIcon(iconEntrenador);

            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_lblEntrenadorMouseExited

    private void lblEntrenadorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEntrenadorMouseEntered
        try {
            URL imagenEntrenador = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/main/ProyectoFinal_LAB1/src/Botones/Botones_pulsados/ENTRENADOR.png");
            ImageIcon iconEntrenador = new ImageIcon(imagenEntrenador);
            lblEntrenador.setIcon(iconEntrenador);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_lblEntrenadorMouseEntered

    private void lblMembresiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMembresiaMouseClicked
        despintarTodos();
        memFlag = true;
        socFlag = false;
        asFlag = false;
        entFlag = false;
        claFlag = false;
        try {
            URL imagenMembresia = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/main/ProyectoFinal_LAB1/src/Botones/Botones_pulsados/MEMBRES%C3%8DA.png");
            ImageIcon iconMembresia = new ImageIcon(imagenMembresia);
            lblMembresia.setIcon(iconMembresia);
        } catch (Exception e) {
        }
        escritorio.removeAll();
        escritorio.repaint();
        VistaMembresia m = new VistaMembresia();
        m.setVisible(true);
        escritorio.add(m);
        m.moveToFront();
        
        try {
            m.setMaximum(true);
        } catch (Exception e) {
        }

    }//GEN-LAST:event_lblMembresiaMouseClicked

    private void lblSociosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSociosMouseClicked
        despintarTodos();
        memFlag = false;
        socFlag = true;
        asFlag = false;
        entFlag = false;
        claFlag = false;
        try {
            URL imagenSocios = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/main/ProyectoFinal_LAB1/src/Botones/Botones_pulsados/SOCIOS.png");
            ImageIcon iconSocio = new ImageIcon(imagenSocios);
            lblSocios.setIcon(iconSocio);
        } catch (Exception e) {
        }
        escritorio.removeAll();
        escritorio.repaint();
        VistaSocio s = new VistaSocio();
        s.setVisible(true);
        escritorio.add(s);
        s.moveToFront();
        
        try {
            s.setMaximum(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_lblSociosMouseClicked

    private void lblClasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClasesMouseClicked
        despintarTodos();
        memFlag = false;
        socFlag = false;
        asFlag = false;
        entFlag = false;
        claFlag = true;
        try {
            URL imagenSocios = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/main/ProyectoFinal_LAB1/src/Botones/Botones_pulsados/CLASES.png");
            ImageIcon iconSocio = new ImageIcon(imagenSocios);
            lblClases.setIcon(iconSocio);
        } catch (Exception e) {
        }
        escritorio.removeAll();
        escritorio.repaint();
        VistaClase c = new VistaClase();
        c.setVisible(true);
        escritorio.add(c);
        c.moveToFront();
        
        try {
            c.setMaximum(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_lblClasesMouseClicked

    private void lblAsistenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAsistenciaMouseClicked
        despintarTodos();
        memFlag = false;
        socFlag = false;
        asFlag = true;
        entFlag = false;
        claFlag = false;
        try {
            URL imagenSocios = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/main/ProyectoFinal_LAB1/src/Botones/Botones_pulsados/ASISTENCIA.png");
            ImageIcon iconSocio = new ImageIcon(imagenSocios);
            lblAsistencia.setIcon(iconSocio);
        } catch (Exception e) {
        }
        escritorio.removeAll();
        escritorio.repaint();
        VistaAsisencia a = new VistaAsisencia();
        a.setVisible(true);
        escritorio.add(a);
        a.moveToFront();
        
        try {
            a.setMaximum(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_lblAsistenciaMouseClicked

    private void lblEntrenadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEntrenadorMouseClicked
        despintarTodos();
        memFlag = false;
        socFlag = false;
        asFlag = false;
        entFlag = true;
        claFlag = false;
        try {
            URL imagenSocios = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/main/ProyectoFinal_LAB1/src/Botones/Botones_pulsados/ENTRENADOR.png");
            ImageIcon iconSocio = new ImageIcon(imagenSocios);
            lblEntrenador.setIcon(iconSocio);
        } catch (Exception e) {
        }
        escritorio.removeAll();
        escritorio.repaint();
        Enrenador e = new Enrenador();
        e.setVisible(true);
        escritorio.add(e);
        e.moveToFront();
        
        try {
            e.setMaximum(true);
        } catch (Exception f) {
        }
        
    }//GEN-LAST:event_lblEntrenadorMouseClicked

    public void despintarTodos() {
        //membresia
        try {
            URL imagenMembresia = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/37fa8fa4d270cd25a3339014b742db8329d0ec87/ProyectoFinal_LAB1/Botones/Botones_sin_pulsar/MEMBRES%C3%8DA_MENU.png");
            ImageIcon iconMembresia = new ImageIcon(imagenMembresia);
            lblMembresia.setIcon(iconMembresia);
        } catch (Exception e) {
        }
        //socio
        try {
            URL imagenSocios = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/37fa8fa4d270cd25a3339014b742db8329d0ec87/ProyectoFinal_LAB1/Botones/Botones_sin_pulsar/SOCIOS_MENU.png");
            ImageIcon iconSocio = new ImageIcon(imagenSocios);
            lblSocios.setIcon(iconSocio);
        } catch (Exception e) {
        }
        //clases
        try {
            URL imagenClases = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/main/ProyectoFinal_LAB1/src/Botones/Botones_sin_pulsar/CLASES_MENU.png");
            ImageIcon iconClase = new ImageIcon(imagenClases);
            lblClases.setIcon(iconClase);
        } catch (Exception e) {
        }
        //asistencia
        try {
            URL imagenAsistencia = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/main/ProyectoFinal_LAB1/src/Botones/Botones_sin_pulsar/ASISTENCIA_MENU.png");
            ImageIcon iconAsistencia = new ImageIcon(imagenAsistencia);
            lblAsistencia.setIcon(iconAsistencia);
        } catch (Exception e) {
        }
        // entrenador
        try {
            URL imagenEntrenador = new URL("https://raw.githubusercontent.com/FMenichetti/TrabajoFinal-LAB1/37fa8fa4d270cd25a3339014b742db8329d0ec87/ProyectoFinal_LAB1/Botones/Botones_sin_pulsar/ENTRENADOR_MENU.png");
            ImageIcon iconEntrenador = new ImageIcon(imagenEntrenador);
            lblEntrenador.setIcon(iconEntrenador);

        } catch (Exception e) {
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel escritorio;
    private javax.swing.JPanel jpFondoBtn;
    private javax.swing.JLabel lblAsistencia;
    private javax.swing.JLabel lblClases;
    private javax.swing.JLabel lblEntrenador;
    private javax.swing.JLabel lblMembresia;
    private javax.swing.JLabel lblSocios;
    // End of variables declaration//GEN-END:variables
}
