package Vistas;

import AccesoDatos.AccesoMembresia;
import Entidades.Membresia;
import java.sql.Date;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

public class VistaMembresia extends javax.swing.JInternalFrame {

    //Atributos
    private AccesoMembresia accesoMembresia;

    public VistaMembresia() {
        initComponents();
        accesoMembresia = new AccesoMembresia();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
    }

    //Metodos
    
    //cargar datos a los campos de textos
    private void cargarDatos(Membresia membresia) {
        if (membresia != null) {
            txtIdMembresia.setText(String.valueOf(membresia.getIdMembresia()));
            txtCantidadPases.setText(String.valueOf(membresia.getCantidadPases()));
            
            //Convertir LocalDate a Date
            Date fechaInicio = Date.valueOf(membresia.getFechaInicio());
            Date fechaFin = Date.valueOf(membresia.getFechaFin());
            
            txtFechaInicio.setDate(fechaInicio);
            txtFechaFin.setDate(fechaFin);
            
            
            txtPrecio.setText(String.valueOf(membresia.getCosto()));
            rBtnEstado.setSelected(membresia.getEstado());

            // El metodo de busqueda de membresias siempre va a traer los que etan activos
            rBtnEstado.setSelected(true);
            
            JOptionPane.showMessageDialog(this, "Membresía cargada correctamente");
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró la membresía");
        }
    }
    
    //bloquear todos los campos excepto txtIdSocio al iniciar
    private void bloquearCamposInicio() {
        txtIdMembresia.setEditable(false);
        txtFechaInicio.setEnabled(false);
        txtFechaFin.setEnabled(false);
        txtCantidadPases.setEditable(false);
        txtPrecio.setEditable(false);
        rBtnEstado.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMembresia = new javax.swing.JLabel();
        lblCantidadPases = new javax.swing.JLabel();
        lblFechaInicio = new javax.swing.JLabel();
        lblFechaFin = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblSocio = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        rBtnEstado = new javax.swing.JRadioButton();
        btnEliminar = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JLabel();
        btnModificar = new javax.swing.JLabel();
        txtIdMembresia = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtIdSocio = new javax.swing.JTextField();
        txtCantidadPases = new javax.swing.JTextField();
        txtFechaFin = new com.toedter.calendar.JDateChooser();
        txtFechaInicio = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        cbMembresias = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTablaMembresia = new javax.swing.JTable();
        txtListarMembresias = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setBorder(null);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        lblMembresia.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblMembresia.setText("ID MEMBRESÍA");
        jPanel1.add(lblMembresia);
        lblMembresia.setBounds(50, 110, 140, 22);

        lblCantidadPases.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCantidadPases.setText("CANTIDAD DE PASES");
        jPanel1.add(lblCantidadPases);
        lblCantidadPases.setBounds(50, 250, 184, 22);

        lblFechaInicio.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblFechaInicio.setText("FECHA INICIO");
        jPanel1.add(lblFechaInicio);
        lblFechaInicio.setBounds(50, 330, 130, 22);

        lblFechaFin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblFechaFin.setText("FECHA FIN");
        jPanel1.add(lblFechaFin);
        lblFechaFin.setBounds(50, 400, 100, 22);

        lblEstado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblEstado.setText("ESTADO");
        jPanel1.add(lblEstado);
        lblEstado.setBounds(50, 550, 80, 22);

        lblSocio.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblSocio.setText("ID SOCIO");
        jPanel1.add(lblSocio);
        lblSocio.setBounds(50, 180, 90, 22);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Botones_internos/BUSCAR.png"))); // NOI18N
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });
        jPanel1.add(btnBuscar);
        btnBuscar.setBounds(340, 140, 160, 70);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel3.setText("MEMBRESÍA");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(180, 20, 178, 36);

        lblPrecio.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblPrecio.setText("PRECIO");
        jPanel1.add(lblPrecio);
        lblPrecio.setBounds(50, 480, 80, 22);
        jPanel1.add(rBtnEstado);
        rBtnEstado.setBounds(160, 550, 19, 20);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Botones_internos/ELIMINAR_2_PULSADO.png"))); // NOI18N
        jPanel1.add(btnEliminar);
        btnEliminar.setBounds(400, 600, 110, 50);

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Botones_internos/NUEVO.png"))); // NOI18N
        jPanel1.add(btnNuevo);
        btnNuevo.setBounds(30, 600, 110, 50);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Botones_internos/GUARDAR.png"))); // NOI18N
        jPanel1.add(btnGuardar);
        btnGuardar.setBounds(150, 600, 110, 50);

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Botones_internos/MODIFICAR.png"))); // NOI18N
        jPanel1.add(btnModificar);
        btnModificar.setBounds(270, 600, 110, 50);

        txtIdMembresia.setBackground(new java.awt.Color(28, 89, 59));
        txtIdMembresia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtIdMembresia.setBorder(null);
        jPanel1.add(txtIdMembresia);
        txtIdMembresia.setBounds(200, 100, 60, 30);

        txtPrecio.setBackground(new java.awt.Color(28, 89, 59));
        txtPrecio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPrecio.setBorder(null);
        jPanel1.add(txtPrecio);
        txtPrecio.setBounds(130, 470, 100, 30);

        txtIdSocio.setBackground(new java.awt.Color(28, 89, 59));
        txtIdSocio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtIdSocio.setBorder(null);
        jPanel1.add(txtIdSocio);
        txtIdSocio.setBounds(150, 170, 60, 30);

        txtCantidadPases.setBackground(new java.awt.Color(28, 89, 59));
        txtCantidadPases.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCantidadPases.setBorder(null);
        jPanel1.add(txtCantidadPases);
        txtCantidadPases.setBounds(250, 240, 60, 30);

        txtFechaFin.setBackground(new java.awt.Color(28, 89, 59));
        txtFechaFin.setDateFormatString("dd MM yyyy");
        txtFechaFin.setInheritsPopupMenu(true);
        txtFechaFin.setOpaque(false);
        jPanel1.add(txtFechaFin);
        txtFechaFin.setBounds(180, 400, 150, 26);

        txtFechaInicio.setBackground(new java.awt.Color(28, 89, 59));
        txtFechaInicio.setDateFormatString("dd/MM/yyyy");
        txtFechaInicio.setInheritsPopupMenu(true);
        txtFechaInicio.setOpaque(false);
        jPanel1.add(txtFechaInicio);
        txtFechaInicio.setBounds(190, 330, 150, 26);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 530, 680);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(null);

        cbMembresias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cbMembresias);
        cbMembresias.setBounds(246, 90, 167, 26);

        tblTablaMembresia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTablaMembresia);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(44, 152, 407, 463);

        txtListarMembresias.setText("Escriba aquí...");
        jPanel2.add(txtListarMembresias);
        txtListarMembresias.setBounds(22, 80, 206, 46);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel2.setText("LISTA DE MEMBRESÍAS");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(75, 17, 338, 36);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(532, 0, 510, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        if (txtIdSocio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ERROR: El campo ID Socio está vacío");
        } else {
            try {
                int id = Integer.valueOf(txtIdSocio.getText());
                Membresia membresia = accesoMembresia.buscarMembresiaPorIdSocio(id);
                cargarDatos(membresia);
                
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "Ingrese un ID válido");
            } catch (Exception a) {
                JOptionPane.showMessageDialog(rootPane, "ERROR: " + a);
            }
        }
    }//GEN-LAST:event_btnBuscarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JLabel btnEliminar;
    private javax.swing.JLabel btnGuardar;
    private javax.swing.JLabel btnModificar;
    private javax.swing.JLabel btnNuevo;
    private javax.swing.JComboBox<String> cbMembresias;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCantidadPases;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFechaFin;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblMembresia;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblSocio;
    private javax.swing.JRadioButton rBtnEstado;
    private javax.swing.JTable tblTablaMembresia;
    private javax.swing.JTextField txtCantidadPases;
    private com.toedter.calendar.JDateChooser txtFechaFin;
    private com.toedter.calendar.JDateChooser txtFechaInicio;
    private javax.swing.JTextField txtIdMembresia;
    private javax.swing.JTextField txtIdSocio;
    private javax.swing.JTextField txtListarMembresias;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
