/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import AccesoDatos.AccesoSocio;
import Entidades.Socio;
import javax.swing.JOptionPane;

/**
 *
 * @author Fabri
 */
public class VistaSocio extends javax.swing.JInternalFrame {
    
    private Socio socio = null;
    private AccesoSocio as = null;
    
    public VistaSocio() {
        initComponents();
        as = new AccesoSocio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtIdSocio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblIdSocio = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblDniSocio = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtDniSocio = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JLabel();
        btnModificar = new javax.swing.JLabel();
        rbEstado = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        txtIdSocio.setBackground(new java.awt.Color(28, 89, 59));
        txtIdSocio.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtIdSocio.setForeground(new java.awt.Color(255, 255, 255));
        txtIdSocio.setBorder(null);
        txtIdSocio.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtIdSocio.setOpaque(false);
        jPanel1.add(txtIdSocio);
        txtIdSocio.setBounds(150, 110, 200, 35);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Botones_internos/txtfield_id.png"))); // NOI18N
        jLabel6.setText("jLabel3");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(410, 470, 122, 57);

        lblIdSocio.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblIdSocio.setText("ID SOCIO");
        jPanel1.add(lblIdSocio);
        lblIdSocio.setBounds(25, 110, 120, 35);

        lblNombre.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblNombre.setText("NOMBRE");
        jPanel1.add(lblNombre);
        lblNombre.setBounds(25, 280, 120, 35);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Botones_internos/txtfield_id.png"))); // NOI18N
        jLabel9.setText("jLabel3");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(410, 390, 122, 57);

        lblApellido.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblApellido.setText("APELLIDO");
        jPanel1.add(lblApellido);
        lblApellido.setBounds(25, 330, 120, 35);

        lblEdad.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblEdad.setText("EDAD");
        jPanel1.add(lblEdad);
        lblEdad.setBounds(30, 410, 120, 35);

        lblEstado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblEstado.setText("ESTADO");
        jPanel1.add(lblEstado);
        lblEstado.setBounds(20, 630, 120, 35);

        lblDniSocio.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblDniSocio.setText("DNI SOCIO");
        jPanel1.add(lblDniSocio);
        lblDniSocio.setBounds(25, 190, 120, 35);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel3.setText("MEMBRESÍA");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(230, 20, 178, 35);

        lblCorreo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCorreo.setText("CORREO");
        jPanel1.add(lblCorreo);
        lblCorreo.setBounds(30, 480, 120, 35);

        lblTelefono.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTelefono.setText("TELEFONO");
        jPanel1.add(lblTelefono);
        lblTelefono.setBounds(20, 550, 120, 35);

        txtTelefono.setBackground(new java.awt.Color(28, 89, 59));
        txtTelefono.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(255, 255, 255));
        txtTelefono.setBorder(null);
        txtTelefono.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtTelefono.setOpaque(false);
        jPanel1.add(txtTelefono);
        txtTelefono.setBounds(150, 550, 200, 35);

        txtCorreo.setBackground(new java.awt.Color(28, 89, 59));
        txtCorreo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(255, 255, 255));
        txtCorreo.setBorder(null);
        txtCorreo.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtCorreo.setOpaque(false);
        jPanel1.add(txtCorreo);
        txtCorreo.setBounds(150, 480, 200, 35);

        txtEdad.setBackground(new java.awt.Color(28, 89, 59));
        txtEdad.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtEdad.setForeground(new java.awt.Color(255, 255, 255));
        txtEdad.setBorder(null);
        txtEdad.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtEdad.setOpaque(false);
        jPanel1.add(txtEdad);
        txtEdad.setBounds(150, 410, 200, 35);

        txtApellido.setBackground(new java.awt.Color(28, 89, 59));
        txtApellido.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(255, 255, 255));
        txtApellido.setBorder(null);
        txtApellido.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtApellido.setOpaque(false);
        jPanel1.add(txtApellido);
        txtApellido.setBounds(150, 330, 200, 35);

        txtNombre.setBackground(new java.awt.Color(28, 89, 59));
        txtNombre.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setBorder(null);
        txtNombre.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtNombre.setOpaque(false);
        jPanel1.add(txtNombre);
        txtNombre.setBounds(150, 270, 200, 35);

        txtDniSocio.setBackground(new java.awt.Color(28, 89, 59));
        txtDniSocio.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtDniSocio.setForeground(new java.awt.Color(255, 255, 255));
        txtDniSocio.setBorder(null);
        txtDniSocio.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtDniSocio.setOpaque(false);
        jPanel1.add(txtDniSocio);
        txtDniSocio.setBounds(150, 190, 200, 35);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Botones_internos/ELIMINAR_2_PULSADO.png"))); // NOI18N
        jPanel1.add(btnEliminar);
        btnEliminar.setBounds(320, 690, 100, 40);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Botones_internos/BUSCAR.png"))); // NOI18N
        btnBuscar.setText("jLabel1");
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });
        jPanel1.add(btnBuscar);
        btnBuscar.setBounds(380, 140, 160, 50);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Botones_internos/GUARDAR.png"))); // NOI18N
        jPanel1.add(btnGuardar);
        btnGuardar.setBounds(40, 690, 100, 40);

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Botones_internos/MODIFICAR.png"))); // NOI18N
        jPanel1.add(btnModificar);
        btnModificar.setBounds(180, 690, 100, 40);

        rbEstado.setForeground(new java.awt.Color(60, 63, 65));
        rbEstado.setSelected(true);
        jPanel1.add(rbEstado);
        rbEstado.setBounds(150, 628, 200, 40);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextField3.setText("jTextField3");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel2.setText("LISTA DE MEMBRESÍAS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        // TODO add your handling code here:
        socio = null;
        try {
            
            if (verificarLleno(txtIdSocio.getText())) {
                socio = as.buscarSocio(Integer.parseInt(txtIdSocio.getText()));
            } else if (verificarLleno(txtDniSocio.getText())) {
                socio = as.buscarSocioPorDni(txtDniSocio.getText());
            }else{
                JOptionPane.showMessageDialog(this, "Debe completar el campo Id o Dni para realizar la busqueda");
            }
            if (socio != null) {
                cargarDatosTxt(socio);
            }
        } catch (Exception e) {
            System.out.println("" + e);
        }
        
    }//GEN-LAST:event_btnBuscarMouseClicked

    //Varifica un campo lleno
    private boolean verificarLleno(String txt) {
        return !txt.isEmpty();
    }

    ;
    
    private void cargarDatosTxt(Socio socio) {
        txtIdSocio.setText(String.valueOf(socio.getIdSocio()));
        txtDniSocio.setText(socio.getDni());
        txtNombre.setText(socio.getNombre());
        txtApellido.setText(socio.getApellido());
        txtEdad.setText(String.valueOf(socio.getEdad()));
        txtCorreo.setText(socio.getCorreo());
        txtTelefono.setText(socio.getTelefono());
        rbEstado.setEnabled(socio.isEstado());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JLabel btnEliminar;
    private javax.swing.JLabel btnGuardar;
    private javax.swing.JLabel btnModificar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDniSocio;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblIdSocio;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JRadioButton rbEstado;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDniSocio;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtIdSocio;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
